# Generated by Django 4.0.4 on 2022-06-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_rename_time_create_planet_time_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='photo',
        ),
    ]
