# Generated by Django 4.0.4 on 2022-06-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='time_create',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='time_update',
            new_name='time_updated',
        ),
    ]
