# Generated by Django 4.0.4 on 2022-06-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_remove_planet_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='content',
            new_name='context',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='time_updated',
        ),
        migrations.AddField(
            model_name='planet',
            name='author',
            field=models.CharField(default='Guest', max_length=30),
        ),
        migrations.AddField(
            model_name='planet',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
